name: cheeseball
description: A crypto tracker app with real-time data and charts

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  fl_chart: ^1.1.1
  # ... other dependencies
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Web configuration at ROOT level (not under flutter)
web:
  renderer: html

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/